language: php

php:

  - 7.0

services:
  - mysql

variables:
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: test
  MYSQL_ALLOW_EMPTY_PASSWORD: '1'

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database test;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan vendor:publish
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - php artisan db:seed
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache